name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version number for the release'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create release ZIP
      run: |
        mkdir release
        cp -R . release/
        cd release
        zip -r ../${GITHUB_REPOSITORY##*/}-${GITHUB_SHA}.zip .
      shell: bash

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Upload release ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-zip
        path: ${GITHUB_REPOSITORY##*/}-${GITHUB_SHA}.zip

    - name: Notify Completion
      run: echo "Release created and ZIP uploaded successfully."
